-   id: cython-lint
    name: cython-lint
    description: Lint Cython files
    entry: cython-lint
    language: python
    types: [cython]
-   id: double-quote-strings
    name: fix single-quoted strings
    description: replaces single-quoted strings with double-quoted strings.
    entry: double-quote-strings
    language: python
    types: [cython]
